### ISSUE TITLE
Biblatex bibliograpy error

### ISSUE THREAD

**Issue by keaganbester** [ChemEngUP/ce-up-latex-templates#12]
The default bibliography entry display style is in error for numerous categories.

For example, bibliography entries as quoted from the style guide:
Mandersloot, W (2003), "Scitech communication," Chemical Technology, October, 33.

As quoted from the current commit:
Mandersloot, Wim (2003). "SciTech Communication". In: Chemical Technology October,
p. 33.

Noticed issues: 
- the "In:" descriptor precedes journal titles and patent fields
- There is no deliminator between journal titles and dates
- "p." and "pp." notation present in page number fields
- Certain first names are not shortening, noticed with names shorter than 4 letters. Biblatex auto-shortening rules agree with 3 letters or less not being shortened.
- Initials are delimited with a space instead, rather than not being delimited
- Patent structure alters slightly in entirety. "Assigned to" descriptor is missing, patent number not italicised. 

Manual changes of the bib style file in the preamble should be on their way today or tomorrow.

@alchemyst Should I attempt creating a custom style file (bbt or bbx format I think) similar to the chemeng,bst file of the BibTex setup or are preamble customisations acceptable?

**Comment by alchemyst** [comment]
My approach has always been to get as close as I can without doing too much micro-customisation. It's honestly not worth one's time to customise too much. If one must customise, I prefer a single file to preamble customisation. If the style file is harder than the preamble customisation, at least `\include` the stuff rather than having it in the main document. You may find help in this endeavour by asking a question on tex.stackexchange.com

**Comment by keaganbester** [comment]
After a few hours on tex.SX I think I have come up with a preliminary customisation. Changes that would normally be placed in the preamble can be placed in the config file biblatex.cfg in the directory of the tex file being compiled.

I have managed to account for all of the noted issues above in #13, and I can add comments to the config file if it will add value to further customisation.
