### ISSUE TITLE
Overleaf and Biblatex

### ISSUE THREAD

**Issue by keaganbester** [ChemEngUP/ce-up-latex-templates#15]
Through the CPJ group work and conversation with other TeX users in our year I have found that Overleaf does not have full compatibility with biblatex.

This is not the concern of this package, but I have noted some basic fixes that do allow some use of this package. 

The import statement placed in upreport.sty can be modified to the following
`\usepackage[style=authoryear, dashed=false, backend=biber, maxbibnames=99,
citetracker=true, maxcitenames=2]{biblatex}'

The implication with this fix is that author first names are not initialised automatically. The reduction of initials must be done manually in the bib file.

I would like to see group projects conducted in LaTeX in future and so I will monitor the biblatex issues in Overleaf and try find a solution that does work on any compiler.

**Comment by alchemyst** [comment]
I'm keen to close this issue, but I'm still getting this warning on Overleaf when I upload the 2017b tag  version

```
./report_template.tex:27:
Package biblatex Warning: Conflicting options.
(biblatex)                'giveninits' conflicts with 'uniquename=full'.
(biblatex)                Setting 'uniquename=init' on input line 27.

```
