### ISSUE TITLE
Fix hard-coded pagenumber

### ISSUE THREAD

**Issue by alchemyst** [ChemEngUP/ce-up-latex-templates#2]
In the master file, we use a hard-code page number (3) for the page after the synopsis. This should be flexible.

**Comment by keaganbester** [comment]
I cannot find a specific point in the style guide that refers to page number styling, so I am using the demo page setup in Section 3.2.1 for all of the points stated below:
- For the report only, a cover page and title page are included without page numbering, but the count is started on the cover page (1, 2),
- The title is repeated on the next page (3) and the synopsis is written.
- After the synopsis comes the table of content, without page numbering,
- After which comes the nomenclature, list of figures and tables.

If the page numbering needs to be flexible, then is the solution to start the count on the cover page and hide the numbering? If I omit the hard-coding of the synopsis page (3) then numbering starts at (1) for that page and this is not correct according to the style guide.

I understand the possibility of the flexible page numbering but I can't think of any particular information that would be placed before the synopsis to extend page numbering.

**Comment by alchemyst** [comment]
Fixed by #4
