### ISSUE TITLE
References not showing correctly

### ISSUE THREAD

**Issue by AlgorithmicAmoeba** [ChemEngUP/ce-up-latex-templates#22]
I downloaded the repository and ran the following:
```
python samplefigure.py
pdflatex report_template
bibtex report_template
makeindex report_template.nlo -s nomencl.ist -o report_template.nls
pdflatex report_template
pdflatex report_template
```
When I opened the `report_template.pdf` file, I noticed that the citations appear to not be showing correctly:
![image](https://user-images.githubusercontent.com/29543948/40265896-50b813c6-5b41-11e8-9b92-62c9901858ed.png)

I would have expected the output to show the authors' surnames and the year in a format like ```(Bruckman and Mandersloot; 1998)```.

**Comment by alchemyst** [comment]
The problem was with the instructions in the README. I have fixed them now to refer to biber instead of bibtex.

**Comment by alchemyst** [comment]
You should also just be able to do `latexmk` to run the correct commands in the correct order.
